### ISSUE TITLE
Incorrect Rendering & unaccessible uplot object

### ISSUE THREAD

**Issue by nielsuit227** [Venryx/react-uplot#2]
Hi, I have some rendering issues with a stream as shown below. I'm on 1.6.15, and using it in React. Now my setup is a bit unique I'd say, so bear with me. 
I have a main function that calls an API every 5 seconds and updates the data, for which I use Reacts `useRef`. This main function renders a secondary function in which all the uPlot stuff happens. The data is parsed from main function to secondary (uPlot function), and most often this goes well. However, there are two big annoyances. Firstly, I cannot access the uPlot object in its function, and secondly, the rendering is sporadically incorrect. 

Main function:
```javascript
import React, {useRef, useEffect} from 'react';
import MyUplot from './MyUplot.js';


export default function MainFuction(props) {
    const data = useRef();
    
    // Only run on component mount
    useEffect(() => {
        const interval = setInterval(getData, 5000);
        return () => clearInterval(interval);
    }, []);

    function getData() {
        data.current = someAPI();
    }

    return <MyUplot data={data.current} />
```

uPlot function:
```javascript
import React from 'react';
import UplotReact from 'uplot-react';


export default function MyUplot(props) {
    let data = props.data;
    let graph;

    const opts = {
        ...
        hooks: {
            ready: [
                u => {
                    uGraph = u;
                }
            ]
        }
    };

   return <UplotReact options={opts} data={data}/>
```
![image](https://user-images.githubusercontent.com/34714661/140104749-26c609a5-3593-4566-8103-c667e9f88949.png)

**Comment by Venryx** [comment]
The `uplot-react` library (as referenced in your code) is different than this `react-uplot` library.

I suggest recreating this issue in the `react-uplot` GitHub here: https://github.com/skalinichev/uplot-wrappers

(And here is its npm page: https://www.npmjs.com/package/uplot-react)
